#############################################################################
# Makefile for building: termux-pkg-manager
# Generated by qmake (3.1) (Qt 5.12.11)
# Project:  termux-pkg-manager.pro
# Template: app
# Command: /data/data/com.termux/files/usr/bin/qmake -o Makefile termux-pkg-manager.pro PREFIX=/data/data/com.termux/files/usr
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -I/data/data/com.termux/files/usr/include -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -I/data/data/com.termux/files/usr/include -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../usr/include/QtWidgets -I../../../../usr/include/QtGui -I../../../../usr/include/QtCore -I. -I. -I../../../../usr/lib/qt/mkspecs/termux
QMAKE         = /data/data/com.termux/files/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /data/data/com.termux/files/usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /data/data/com.termux/files/usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = termux-pkg-manager1.0.0
DISTDIR = /data/data/com.termux/files/home/Documents/qt-apps/termux-pkg-manager-qt/.tmp/termux-pkg-manager1.0.0
LINK          = clang++
LFLAGS        = -L/data/data/com.termux/files/usr/lib
LIBS          = $(SUBLIBS) /data/data/com.termux/files/usr/lib/libQt5Widgets.so /data/data/com.termux/files/usr/lib/libQt5Gui.so /data/data/com.termux/files/usr/lib/libQt5Core.so   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = org.termux-pkg-manager-qt.desktop \
		../../../../usr/lib/qt/mkspecs/features/spec_pre.prf \
		../../../../usr/lib/qt/mkspecs/common/unix.conf \
		../../../../usr/lib/qt/mkspecs/common/linux.conf \
		../../../../usr/lib/qt/mkspecs/common/sanitize.conf \
		../../../../usr/lib/qt/mkspecs/common/gcc-base.conf \
		../../../../usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		../../../../usr/lib/qt/mkspecs/common/clang.conf \
		../../../../usr/lib/qt/mkspecs/qconfig.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../usr/lib/qt/mkspecs/features/qt_functions.prf \
		../../../../usr/lib/qt/mkspecs/features/qt_config.prf \
		../../../../usr/lib/qt/mkspecs/termux/qmake.conf \
		../../../../usr/lib/qt/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../../../usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		../../../../usr/lib/qt/mkspecs/features/toolchain.prf \
		../../../../usr/lib/qt/mkspecs/features/default_pre.prf \
		../../../../usr/lib/qt/mkspecs/features/resolve_config.prf \
		../../../../usr/lib/qt/mkspecs/features/default_post.prf \
		../../../../usr/lib/qt/mkspecs/features/warn_on.prf \
		../../../../usr/lib/qt/mkspecs/features/qt.prf \
		../../../../usr/lib/qt/mkspecs/features/resources.prf \
		../../../../usr/lib/qt/mkspecs/features/moc.prf \
		../../../../usr/lib/qt/mkspecs/features/uic.prf \
		../../../../usr/lib/qt/mkspecs/features/unix/thread.prf \
		../../../../usr/lib/qt/mkspecs/features/qmake_use.prf \
		../../../../usr/lib/qt/mkspecs/features/file_copies.prf \
		../../../../usr/lib/qt/mkspecs/features/testcase_targets.prf \
		../../../../usr/lib/qt/mkspecs/features/exceptions.prf \
		../../../../usr/lib/qt/mkspecs/features/yacc.prf \
		../../../../usr/lib/qt/mkspecs/features/lex.prf \
		termux-pkg-manager.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = termux-pkg-manager
DESTDIR       = 
TARGET        = termux-pkg-manager


first: all
####### Build rules

termux-pkg-manager: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: termux-pkg-manager.pro ../../../../usr/lib/qt/mkspecs/termux/qmake.conf ../../../../usr/lib/qt/mkspecs/features/spec_pre.prf \
		../../../../usr/lib/qt/mkspecs/common/unix.conf \
		../../../../usr/lib/qt/mkspecs/common/linux.conf \
		../../../../usr/lib/qt/mkspecs/common/sanitize.conf \
		../../../../usr/lib/qt/mkspecs/common/gcc-base.conf \
		../../../../usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		../../../../usr/lib/qt/mkspecs/common/clang.conf \
		../../../../usr/lib/qt/mkspecs/qconfig.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../usr/lib/qt/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../usr/lib/qt/mkspecs/features/qt_functions.prf \
		../../../../usr/lib/qt/mkspecs/features/qt_config.prf \
		../../../../usr/lib/qt/mkspecs/termux/qmake.conf \
		../../../../usr/lib/qt/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../../../usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		../../../../usr/lib/qt/mkspecs/features/toolchain.prf \
		../../../../usr/lib/qt/mkspecs/features/default_pre.prf \
		../../../../usr/lib/qt/mkspecs/features/resolve_config.prf \
		../../../../usr/lib/qt/mkspecs/features/default_post.prf \
		../../../../usr/lib/qt/mkspecs/features/warn_on.prf \
		../../../../usr/lib/qt/mkspecs/features/qt.prf \
		../../../../usr/lib/qt/mkspecs/features/resources.prf \
		../../../../usr/lib/qt/mkspecs/features/moc.prf \
		../../../../usr/lib/qt/mkspecs/features/uic.prf \
		../../../../usr/lib/qt/mkspecs/features/unix/thread.prf \
		../../../../usr/lib/qt/mkspecs/features/qmake_use.prf \
		../../../../usr/lib/qt/mkspecs/features/file_copies.prf \
		../../../../usr/lib/qt/mkspecs/features/testcase_targets.prf \
		../../../../usr/lib/qt/mkspecs/features/exceptions.prf \
		../../../../usr/lib/qt/mkspecs/features/yacc.prf \
		../../../../usr/lib/qt/mkspecs/features/lex.prf \
		termux-pkg-manager.pro
	$(QMAKE) -o Makefile termux-pkg-manager.pro PREFIX=/data/data/com.termux/files/usr
../../../../usr/lib/qt/mkspecs/features/spec_pre.prf:
../../../../usr/lib/qt/mkspecs/common/unix.conf:
../../../../usr/lib/qt/mkspecs/common/linux.conf:
../../../../usr/lib/qt/mkspecs/common/sanitize.conf:
../../../../usr/lib/qt/mkspecs/common/gcc-base.conf:
../../../../usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
../../../../usr/lib/qt/mkspecs/common/clang.conf:
../../../../usr/lib/qt/mkspecs/qconfig.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../usr/lib/qt/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../usr/lib/qt/mkspecs/features/qt_functions.prf:
../../../../usr/lib/qt/mkspecs/features/qt_config.prf:
../../../../usr/lib/qt/mkspecs/termux/qmake.conf:
../../../../usr/lib/qt/mkspecs/features/spec_post.prf:
../.qmake.stash:
../../../../usr/lib/qt/mkspecs/features/exclusive_builds.prf:
../../../../usr/lib/qt/mkspecs/features/toolchain.prf:
../../../../usr/lib/qt/mkspecs/features/default_pre.prf:
../../../../usr/lib/qt/mkspecs/features/resolve_config.prf:
../../../../usr/lib/qt/mkspecs/features/default_post.prf:
../../../../usr/lib/qt/mkspecs/features/warn_on.prf:
../../../../usr/lib/qt/mkspecs/features/qt.prf:
../../../../usr/lib/qt/mkspecs/features/resources.prf:
../../../../usr/lib/qt/mkspecs/features/moc.prf:
../../../../usr/lib/qt/mkspecs/features/uic.prf:
../../../../usr/lib/qt/mkspecs/features/unix/thread.prf:
../../../../usr/lib/qt/mkspecs/features/qmake_use.prf:
../../../../usr/lib/qt/mkspecs/features/file_copies.prf:
../../../../usr/lib/qt/mkspecs/features/testcase_targets.prf:
../../../../usr/lib/qt/mkspecs/features/exceptions.prf:
../../../../usr/lib/qt/mkspecs/features/yacc.prf:
../../../../usr/lib/qt/mkspecs/features/lex.prf:
termux-pkg-manager.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile termux-pkg-manager.pro PREFIX=/data/data/com.termux/files/usr

qmake_all: FORCE


all: Makefile termux-pkg-manager

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/
	$(COPY_FILE) --parents termux-pkg-manager_en_US.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../usr/lib/qt/mkspecs/features/data/dummy.cpp
	clang++ -pipe -I/data/data/com.termux/files/usr/include -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../../usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../../../usr/include/QtWidgets/QMainWindow \
		../../../../usr/include/QtWidgets/qmainwindow.h \
		moc_predefs.h \
		../../../../usr/bin/moc
	/data/data/com.termux/files/usr/bin/moc $(DEFINES) --include /data/data/com.termux/files/home/Documents/qt-apps/termux-pkg-manager-qt/moc_predefs.h -I/data/data/com.termux/files/usr/lib/qt/mkspecs/termux -I/data/data/com.termux/files/home/Documents/qt-apps/termux-pkg-manager-qt -I/data/data/com.termux/files/usr/include/QtWidgets -I/data/data/com.termux/files/usr/include/QtGui -I/data/data/com.termux/files/usr/include/QtCore -I/data/data/com.termux/files/usr/include/c++/v1 -I/data/data/com.termux/files/usr/lib/clang/12.0.1/include -I/data/data/com.termux/files/usr/include/arm-linux-androideabi -I/data/data/com.termux/files/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../../usr/bin/uic
	/data/data/com.termux/files/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../../usr/include/QtWidgets/QMainWindow \
		../../../../usr/include/QtWidgets/qmainwindow.h \
		../../../../usr/include/QtWidgets/QApplication \
		../../../../usr/include/QtWidgets/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../../usr/include/QtWidgets/QMainWindow \
		../../../../usr/include/QtWidgets/qmainwindow.h \
		ui_mainwindow.h \
		../../../../usr/include/QtCore/QProcess \
		../../../../usr/include/QtCore/qprocess.h \
		../../../../usr/include/QtWidgets/QMessageBox \
		../../../../usr/include/QtWidgets/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/data/data/com.termux/files/usr/termux-pkg-manager/bin || mkdir -p $(INSTALL_ROOT)/data/data/com.termux/files/usr/termux-pkg-manager/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/data/data/com.termux/files/usr/termux-pkg-manager/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/data/data/com.termux/files/usr/termux-pkg-manager/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/data/data/com.termux/files/usr/termux-pkg-manager/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/data/data/com.termux/files/usr/termux-pkg-manager/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

